const fs = require('fs');
const path = require('path');

// Site configurations for top 20 domains
const siteConfigs = {
  'damecoins': {
    domain: 'damecoins.com',
    title: 'DameCoins - Cryptocurrency Exchange Platform',
    description: 'Buy and sell cryptocurrencies instantly with DameCoins',
    heading: 'Your Gateway to Cryptocurrency',
    tagline: 'Buy, Sell, and Trade Digital Assets with Confidence',
    cta_text: 'Start Trading Now',
    primary_color: '#f7931a',
    gradient_start: '#f7931a',
    gradient_end: '#ff6b6b',
    features_heading: 'Why Choose DameCoins?',
    feature1_title: 'Instant Trading',
    feature1_desc: 'Buy and sell cryptocurrencies in seconds with competitive rates',
    feature2_title: 'Secure Platform',
    feature2_desc: 'Bank-level security with cold storage and 2FA protection',
    feature3_title: '24/7 Support',
    feature3_desc: 'Round-the-clock customer support in multiple languages',
    icon1: '⚡',
    icon2: '🔒',
    icon3: '💬'
  },
  'gptcoins': {
    domain: 'gptcoins.com',
    title: 'GPTCoins - AI-Powered Crypto Trading',
    description: 'Leverage GPT AI for smarter cryptocurrency trading',
    heading: 'AI-Powered Crypto Trading',
    tagline: 'Let Artificial Intelligence Optimize Your Portfolio',
    cta_text: 'Start AI Trading',
    primary_color: '#00d4ff',
    gradient_start: '#667eea',
    gradient_end: '#764ba2',
    features_heading: 'Smart Trading Features',
    feature1_title: 'AI Analysis',
    feature1_desc: 'GPT-powered market analysis and predictions',
    feature2_title: 'Auto Trading',
    feature2_desc: 'Automated trading strategies based on AI insights',
    feature3_title: 'Risk Management',
    feature3_desc: 'Intelligent portfolio optimization and risk assessment',
    icon1: '🤖',
    icon2: '📈',
    icon3: '🛡️'
  },
  'detectar': {
    domain: 'detectar.ai',
    title: 'Detectar.ai - AI Content Detection',
    description: 'Advanced AI detection and verification platform',
    heading: 'Detect AI-Generated Content',
    tagline: 'Ensure Authenticity in the Age of AI',
    cta_text: 'Try Detection Now',
    primary_color: '#10b981',
    gradient_start: '#10b981',
    gradient_end: '#3b82f6',
    features_heading: 'Detection Capabilities',
    feature1_title: 'Text Analysis',
    feature1_desc: 'Identify AI-generated text with 99% accuracy',
    feature2_title: 'Image Verification',
    feature2_desc: 'Detect deepfakes and AI-generated images',
    feature3_title: 'Real-time API',
    feature3_desc: 'Integrate detection into your workflow',
    icon1: '🔍',
    icon2: '🖼️',
    icon3: '⚡'
  },
  'empleados': {
    domain: 'empleados.ai',
    title: 'Empleados.ai - AI HR Management',
    description: 'Intelligent employee management and recruitment platform',
    heading: 'AI-Powered HR Solutions',
    tagline: 'Transform Your Workforce Management',
    cta_text: 'Get Started Free',
    primary_color: '#8b5cf6',
    gradient_start: '#8b5cf6',
    gradient_end: '#ec4899',
    features_heading: 'HR Automation Features',
    feature1_title: 'Smart Recruiting',
    feature1_desc: 'AI-powered candidate matching and screening',
    feature2_title: 'Performance Analytics',
    feature2_desc: 'Data-driven employee performance insights',
    feature3_title: 'Automated Onboarding',
    feature3_desc: 'Streamlined onboarding with AI assistance',
    icon1: '👥',
    icon2: '📊',
    icon3: '🚀'
  },
  'instantvirtualcards': {
    domain: 'instantvirtualcards.com',
    title: 'Instant Virtual Cards - Digital Payment Solutions',
    description: 'Create virtual debit cards instantly for online payments',
    heading: 'Virtual Cards in Seconds',
    tagline: 'Secure Online Payments Made Simple',
    cta_text: 'Create Card Now',
    primary_color: '#059669',
    gradient_start: '#059669',
    gradient_end: '#0891b2',
    features_heading: 'Virtual Card Benefits',
    feature1_title: 'Instant Creation',
    feature1_desc: 'Generate virtual cards in seconds, no waiting',
    feature2_title: 'Maximum Security',
    feature2_desc: 'Single-use cards for maximum payment security',
    feature3_title: 'Global Acceptance',
    feature3_desc: 'Works with any online merchant worldwide',
    icon1: '💳',
    icon2: '🔐',
    icon3: '🌍'
  },
  'damepay': {
    domain: 'damepay.com',
    title: 'DamePay - Payment Gateway Solutions',
    description: 'Accept payments globally with our secure gateway',
    heading: 'Global Payment Gateway',
    tagline: 'Accept Payments from Anywhere, Anytime',
    cta_text: 'Start Accepting Payments',
    primary_color: '#7c3aed',
    gradient_start: '#7c3aed',
    gradient_end: '#2563eb',
    features_heading: 'Payment Solutions',
    feature1_title: 'Multi-Currency',
    feature1_desc: 'Accept payments in 150+ currencies',
    feature2_title: 'Instant Settlement',
    feature2_desc: 'Get your money faster with instant payouts',
    feature3_title: 'Fraud Protection',
    feature3_desc: 'Advanced AI-powered fraud detection',
    icon1: '💰',
    icon2: '⚡',
    icon3: '🛡️'
  },
  'gptapikeys': {
    domain: 'gptapikeys.com',
    title: 'GPT API Keys - API Management Platform',
    description: 'Manage and monetize your GPT API access',
    heading: 'GPT API Key Management',
    tagline: 'Simplify Your AI API Infrastructure',
    cta_text: 'Manage APIs Now',
    primary_color: '#10b981',
    gradient_start: '#10b981',
    gradient_end: '#14b8a6',
    features_heading: 'API Management Features',
    feature1_title: 'Key Management',
    feature1_desc: 'Centralized API key creation and management',
    feature2_title: 'Usage Analytics',
    feature2_desc: 'Track API usage and optimize costs',
    feature3_title: 'Rate Limiting',
    feature3_desc: 'Control access with intelligent rate limiting',
    icon1: '🔑',
    icon2: '📈',
    icon3: '⚙️'
  },
  'megacursos': {
    domain: 'megacursos.com',
    title: 'MegaCursos - Online Learning Platform',
    description: 'Access thousands of courses in technology and business',
    heading: 'Learn Without Limits',
    tagline: 'Your Journey to Knowledge Starts Here',
    cta_text: 'Browse Courses',
    primary_color: '#dc2626',
    gradient_start: '#dc2626',
    gradient_end: '#f97316',
    features_heading: 'Learning Features',
    feature1_title: 'Expert Instructors',
    feature1_desc: 'Learn from industry professionals',
    feature2_title: 'Lifetime Access',
    feature2_desc: 'Access your courses anytime, anywhere',
    feature3_title: 'Certificates',
    feature3_desc: 'Earn recognized certificates upon completion',
    icon1: '👨‍🏫',
    icon2: '♾️',
    icon3: '🏆'
  },
  'cryptoupdated': {
    domain: 'cryptoupdated.com',
    title: 'Crypto Updated - Real-time Crypto News',
    description: 'Stay updated with the latest cryptocurrency news and analysis',
    heading: 'Real-Time Crypto News',
    tagline: 'Never Miss a Market Movement',
    cta_text: 'Get Updates Now',
    primary_color: '#f59e0b',
    gradient_start: '#f59e0b',
    gradient_end: '#ef4444',
    features_heading: 'News Features',
    feature1_title: 'Breaking News',
    feature1_desc: 'Real-time updates on market movements',
    feature2_title: 'Expert Analysis',
    feature2_desc: 'In-depth analysis from crypto experts',
    feature3_title: 'Price Alerts',
    feature3_desc: 'Custom alerts for price movements',
    icon1: '📰',
    icon2: '📊',
    icon3: '🔔'
  },
  'gpt-excel': {
    domain: 'gpt-excel.com',
    title: 'GPT Excel - AI-Powered Spreadsheets',
    description: 'Transform Excel with GPT AI capabilities',
    heading: 'Excel Meets AI',
    tagline: 'Supercharge Your Spreadsheets with GPT',
    cta_text: 'Try GPT Excel',
    primary_color: '#10b981',
    gradient_start: '#10b981',
    gradient_end: '#06b6d4',
    features_heading: 'AI Excel Features',
    feature1_title: 'Formula Generation',
    feature1_desc: 'Generate complex formulas with natural language',
    feature2_title: 'Data Analysis',
    feature2_desc: 'AI-powered insights from your data',
    feature3_title: 'Automation',
    feature3_desc: 'Automate repetitive tasks with AI',
    icon1: '📊',
    icon2: '🤖',
    icon3: '⚡'
  },
  'autoword': {
    domain: 'autoword.ai',
    title: 'AutoWord.ai - AI Content Generation',
    description: 'Generate high-quality content automatically with AI',
    heading: 'AI Content Creation',
    tagline: 'Write Better, Faster, Smarter',
    cta_text: 'Start Writing',
    primary_color: '#6366f1',
    gradient_start: '#6366f1',
    gradient_end: '#8b5cf6',
    features_heading: 'Content Features',
    feature1_title: 'Blog Posts',
    feature1_desc: 'Generate SEO-optimized blog content',
    feature2_title: 'Social Media',
    feature2_desc: 'Create engaging social media posts',
    feature3_title: 'Email Copy',
    feature3_desc: 'Write compelling email campaigns',
    icon1: '✍️',
    icon2: '📱',
    icon3: '📧'
  },
  'autotinder': {
    domain: 'autotinder.ai',
    title: 'AutoTinder.ai - AI Dating Assistant',
    description: 'Optimize your dating profile with AI',
    heading: 'AI-Powered Dating Success',
    tagline: 'Let AI Help You Find Your Perfect Match',
    cta_text: 'Optimize Profile',
    primary_color: '#ec4899',
    gradient_start: '#ec4899',
    gradient_end: '#f43f5e',
    features_heading: 'Dating AI Features',
    feature1_title: 'Profile Optimization',
    feature1_desc: 'AI-enhanced profile for more matches',
    feature2_title: 'Smart Messaging',
    feature2_desc: 'AI-generated conversation starters',
    feature3_title: 'Match Analysis',
    feature3_desc: 'Compatibility analysis with AI',
    icon1: '❤️',
    icon2: '💬',
    icon3: '🎯'
  },
  'dameapi': {
    domain: 'dameapi.com',
    title: 'DameAPI - API Development Platform',
    description: 'Build, test, and deploy APIs faster',
    heading: 'API Development Made Easy',
    tagline: 'From Concept to Production in Minutes',
    cta_text: 'Build Your API',
    primary_color: '#3b82f6',
    gradient_start: '#3b82f6',
    gradient_end: '#6366f1',
    features_heading: 'API Platform Features',
    feature1_title: 'Visual Builder',
    feature1_desc: 'Design APIs with our visual interface',
    feature2_title: 'Auto Documentation',
    feature2_desc: 'Generate API docs automatically',
    feature3_title: 'Testing Suite',
    feature3_desc: 'Comprehensive API testing tools',
    icon1: '🔧',
    icon2: '📚',
    icon3: '🧪'
  },
  'flywallex': {
    domain: 'flywallex.com',
    title: 'FlyWallex - Digital Wallet Solutions',
    description: 'Your all-in-one digital wallet for global payments',
    heading: 'Digital Wallet Revolution',
    tagline: 'Pay, Send, and Receive Globally',
    cta_text: 'Open Wallet',
    primary_color: '#14b8a6',
    gradient_start: '#14b8a6',
    gradient_end: '#06b6d4',
    features_heading: 'Wallet Features',
    feature1_title: 'Multi-Currency',
    feature1_desc: 'Hold and exchange multiple currencies',
    feature2_title: 'Instant Transfers',
    feature2_desc: 'Send money globally in seconds',
    feature3_title: 'Virtual Cards',
    feature3_desc: 'Generate virtual cards for online shopping',
    icon1: '💼',
    icon2: '🚀',
    icon3: '💳'
  },
  'gateway24h': {
    domain: 'gateway24h.com',
    title: 'Gateway24h - 24/7 Payment Processing',
    description: 'Round-the-clock payment gateway services',
    heading: '24/7 Payment Gateway',
    tagline: 'Never Stop Accepting Payments',
    cta_text: 'Get Started',
    primary_color: '#0891b2',
    gradient_start: '#0891b2',
    gradient_end: '#0ea5e9',
    features_heading: 'Gateway Features',
    feature1_title: '99.9% Uptime',
    feature1_desc: 'Reliable payment processing 24/7',
    feature2_title: 'Global Coverage',
    feature2_desc: 'Accept payments from 200+ countries',
    feature3_title: 'Instant Setup',
    feature3_desc: 'Start accepting payments in minutes',
    icon1: '⏰',
    icon2: '🌍',
    icon3: '⚡'
  },
  'fintechmorning': {
    domain: 'fintechmorning.com',
    title: 'Fintech Morning - Daily Finance News',
    description: 'Start your day with fintech news and insights',
    heading: 'Fintech News Daily',
    tagline: 'Your Morning Dose of Financial Innovation',
    cta_text: 'Subscribe Now',
    primary_color: '#1e40af',
    gradient_start: '#1e40af',
    gradient_end: '#3730a3',
    features_heading: 'News Features',
    feature1_title: 'Daily Briefing',
    feature1_desc: 'Curated fintech news every morning',
    feature2_title: 'Market Analysis',
    feature2_desc: 'Expert insights on market trends',
    feature3_title: 'Industry Reports',
    feature3_desc: 'In-depth fintech industry analysis',
    icon1: '☕',
    icon2: '📈',
    icon3: '📊'
  },
  'visualingo': {
    domain: 'visualingo.app',
    title: 'Visualingo - Visual Language Learning',
    description: 'Learn languages through visual recognition',
    heading: 'Learn Languages Visually',
    tagline: 'See It, Learn It, Speak It',
    cta_text: 'Start Learning',
    primary_color: '#dc2626',
    gradient_start: '#dc2626',
    gradient_end: '#ea580c',
    features_heading: 'Learning Features',
    feature1_title: 'Visual Recognition',
    feature1_desc: 'Learn words through image association',
    feature2_title: 'AR Learning',
    feature2_desc: 'Augmented reality language practice',
    feature3_title: 'Progress Tracking',
    feature3_desc: 'Track your learning journey',
    icon1: '👁️',
    icon2: '📱',
    icon3: '📊'
  },
  'mcp': {
    domain: 'mcp.blue',
    title: 'MCP.blue - Model Context Protocol',
    description: 'Advanced AI model context management',
    heading: 'Model Context Protocol',
    tagline: 'Next-Generation AI Infrastructure',
    cta_text: 'Explore MCP',
    primary_color: '#2563eb',
    gradient_start: '#2563eb',
    gradient_end: '#1e40af',
    features_heading: 'MCP Features',
    feature1_title: 'Context Management',
    feature1_desc: 'Efficient AI model context handling',
    feature2_title: 'Protocol Standards',
    feature2_desc: 'Industry-standard AI protocols',
    feature3_title: 'Integration',
    feature3_desc: 'Seamless AI system integration',
    icon1: '🧠',
    icon2: '🔗',
    icon3: '⚡'
  },
  'sort': {
    domain: 'sort.services',
    title: 'Sort Services - Data Organization Platform',
    description: 'Intelligent data sorting and organization',
    heading: 'Smart Data Sorting',
    tagline: 'Organize Your Data Intelligently',
    cta_text: 'Start Sorting',
    primary_color: '#059669',
    gradient_start: '#059669',
    gradient_end: '#10b981',
    features_heading: 'Sorting Features',
    feature1_title: 'AI Sorting',
    feature1_desc: 'Intelligent data categorization',
    feature2_title: 'Bulk Processing',
    feature2_desc: 'Process millions of records',
    feature3_title: 'Custom Rules',
    feature3_desc: 'Define your own sorting logic',
    icon1: '🗂️',
    icon2: '⚡',
    icon3: '⚙️'
  },
  'agentsai': {
    domain: 'agentsai.ltd',
    title: 'Agents AI - Autonomous AI Agents',
    description: 'Deploy autonomous AI agents for your business',
    heading: 'Autonomous AI Agents',
    tagline: 'Let AI Agents Work for You',
    cta_text: 'Deploy Agents',
    primary_color: '#7c3aed',
    gradient_start: '#7c3aed',
    gradient_end: '#9333ea',
    features_heading: 'Agent Features',
    feature1_title: 'Task Automation',
    feature1_desc: 'Agents that complete tasks autonomously',
    feature2_title: 'Multi-Agent System',
    feature2_desc: 'Deploy multiple specialized agents',
    feature3_title: '24/7 Operation',
    feature3_desc: 'Agents work round the clock',
    icon1: '🤖',
    icon2: '👥',
    icon3: '⏰'
  },
  'default': {
    domain: 'example.com',
    title: 'Coming Soon',
    description: 'This domain is being prepared',
    heading: 'Coming Soon',
    tagline: 'Something Amazing is in the Works',
    cta_text: 'Get Notified',
    primary_color: '#6b7280',
    gradient_start: '#6b7280',
    gradient_end: '#9ca3af',
    features_heading: 'What to Expect',
    feature1_title: 'Innovation',
    feature1_desc: 'Cutting-edge technology solutions',
    feature2_title: 'Quality',
    feature2_desc: 'Premium services and support',
    feature3_title: 'Excellence',
    feature3_desc: 'Commitment to excellence',
    icon1: '🚀',
    icon2: '⭐',
    icon3: '🏆'
  }
};

// Read template
const template = fs.readFileSync(path.join(__dirname, 'shared', 'template.html'), 'utf8');

// Generate sites
Object.keys(siteConfigs).forEach(siteName => {
  const config = siteConfigs[siteName];
  const siteDir = path.join(__dirname, 'sites', siteName);
  
  // Create directory
  if (!fs.existsSync(siteDir)) {
    fs.mkdirSync(siteDir, { recursive: true });
  }
  
  // Replace placeholders
  let html = template;
  Object.keys(config).forEach(key => {
    const placeholder = `{{${key.toUpperCase()}}}`;
    html = html.replace(new RegExp(placeholder, 'g'), config[key]);
  });
  
  // Write file
  fs.writeFileSync(path.join(siteDir, 'index.html'), html);
  console.log(`✅ Generated site for ${config.domain}`);
});

console.log(`\n🎉 Successfully generated ${Object.keys(siteConfigs).length} sites!`);