name = "domains-router"
main = "domains-router.js"
compatibility_date = "2024-12-20"

routes = [
  { pattern = "damecoins.com/*", zone_name = "damecoins.com" },
  { pattern = "gptcoins.com/*", zone_name = "gptcoins.com" },
  { pattern = "detectar.ai/*", zone_name = "detectar.ai" },
  { pattern = "empleados.ai/*", zone_name = "empleados.ai" },
  { pattern = "instantvirtualcards.com/*", zone_name = "instantvirtualcards.com" },
  { pattern = "gptapikeys.com/*", zone_name = "gptapikeys.com" },
  { pattern = "megacursos.com/*", zone_name = "megacursos.com" },
  { pattern = "cryptoupdated.com/*", zone_name = "cryptoupdated.com" },
  { pattern = "gpt-excel.com/*", zone_name = "gpt-excel.com" },
  { pattern = "autoword.ai/*", zone_name = "autoword.ai" },
  { pattern = "autotinder.ai/*", zone_name = "autotinder.ai" },
  { pattern = "dameapi.com/*", zone_name = "dameapi.com" },
  { pattern = "flywallex.com/*", zone_name = "flywallex.com" },
  { pattern = "gateway24h.com/*", zone_name = "gateway24h.com" },
  { pattern = "fintechmorning.com/*", zone_name = "fintechmorning.com" },
  { pattern = "visualingo.app/*", zone_name = "visualingo.app" },
  { pattern = "mcp.blue/*", zone_name = "mcp.blue" },
  { pattern = "sort.services/*", zone_name = "sort.services" },
  { pattern = "agentsai.ltd/*", zone_name = "agentsai.ltd" }
]