name = "domains-monorepo"
compatibility_date = "2024-12-20"

[site]
bucket = "./sites"

[[routes]]
pattern = "damecoins.com/*"
custom_domain = true

[[routes]]
pattern = "gptcoins.com/*"
custom_domain = true

[[routes]]
pattern = "detectar.ai/*"
custom_domain = true

[[routes]]
pattern = "empleados.ai/*"
custom_domain = true

[[routes]]
pattern = "instantvirtualcards.com/*"
custom_domain = true

[[routes]]
pattern = "damepay.com/*"
custom_domain = true

[[routes]]
pattern = "gptapikeys.com/*"
custom_domain = true

[[routes]]
pattern = "megacursos.com/*"
custom_domain = true

[[routes]]
pattern = "cryptoupdated.com/*"
custom_domain = true

[[routes]]
pattern = "gpt-excel.com/*"
custom_domain = true

[[routes]]
pattern = "autoword.ai/*"
custom_domain = true

[[routes]]
pattern = "autotinder.ai/*"
custom_domain = true

[[routes]]
pattern = "dameapi.com/*"
custom_domain = true

[[routes]]
pattern = "flywallex.com/*"
custom_domain = true

[[routes]]
pattern = "gateway24h.com/*"
custom_domain = true

[[routes]]
pattern = "fintechmorning.com/*"
custom_domain = true

[[routes]]
pattern = "visualingo.app/*"
custom_domain = true

[[routes]]
pattern = "mcp.blue/*"
custom_domain = true

[[routes]]
pattern = "sort.services/*"
custom_domain = true

[[routes]]
pattern = "agentsai.ltd/*"
custom_domain = true